### ISSUE TITLE
Question / Potential Suggestion idk

### ISSUE THREAD

**Issue by DJDogster1384** [Sewer56/Riders.Tweakbox#14]
Is there a way to disable the Unlock All feature? Like, is it temporary? And also, when you use Tweakbox, is everything unlocked by default? Sorry, I've not tried it yet.

**Comment by Sewer56** [comment]
Everything is unlocked by default.

You can either disable it by unchecking `Boot to Menu & Unlock All` in Tweakbox Settings or just going back to the title screen and loading a save file.
