### ISSUE TITLE
Bug: I changed some settings, and now it crashes when trying to start it!

### ISSUE THREAD

**Issue by DJDogster1384** [Sewer56/Riders.Tweakbox#16]
The settings I changed were "Boot to Menu and Unlock All" to false, and all the "Boot to stage selection after completing ___." options, and now upon attempting to open the game, it simply does not work, also, when going into fullscreen, I have to click somewhere else for the game to think my cursor is on one of the options, please help! I really wanted to try this out! Here are my settings from the configuration / fixesConfiguration text file.
![image](https://user-images.githubusercontent.com/74204727/121412643-eefc6c00-c932-11eb-8ca4-91b3cfadfa1d.png)

**Comment by Sewer56** [comment]
Nothing looks unusual in this config file. 

Can you provide a crash log? [The documentation provides details on how to do it.](https://sewer56.dev/Riders.Tweakbox/reporting-issues/)

**Comment by DJDogster1384** [comment]
Here's the most recent log of it. I hope this can help!

[2021-06-09 14.53.01 ~ SonicRiders.txt](https://github.com/Sewer56/Riders.Tweakbox/files/6626279/2021-06-09.14.53.01.SonicRiders.txt)

**Comment by DJDogster1384** [comment]
If you're reffering to Crash dumps, I can't find the folder in the Local Appdata

**Comment by DJDogster1384** [comment]
Alright! Thanks for the help!

**Comment by DJDogster1384** [comment]
Umm, wait, now my controls don't work, I'm using Dinput for my controller. A Wired Fighter Pad Pro for the Nintendo Switch (I plugged it into my PC)

**Comment by Sewer56** [comment]
![image](https://user-images.githubusercontent.com/6697380/121418301-b7a5b380-c962-11eb-9f6d-5dba55d6deb3.png)

Use Custom Mapping & Post Process and you should be good.

**Comment by DJDogster1384** [comment]
I just did that, and tried it, but when I press up or down on ANY menu, it just skips to the top, or bottom option, sorry to inconvinience, but could you help?

**Comment by Sewer56** [comment]
If I were to guess, might be something like binding DPAD to stick with stick invert setting set in Post Process mod.
Try to bind the minimum stuff and go from there.

If you need to invert stick direction, check in Post Process.

**Comment by DJDogster1384** [comment]
I'll try, but first, how do I get rid of the binds that I am currently using, to get rid of the DPAD binding? Or do I have to do a different Controller Profile?

**Comment by Sewer56** [comment]
Right click.

**Comment by DJDogster1384** [comment]
Okay, turns out my stick up and down are inverted, but I don't know how to check in Post Process to invert it, if this is a dumb question, it's because I have little experience with Reloaded, so thanks for the help so far!

**Comment by Sewer56** [comment]
It's in the Post Process mod as I mentioned before 
![image](https://user-images.githubusercontent.com/6697380/121426731-cfce0080-c96b-11eb-8f15-22c65e644fa7.png)

**Comment by DJDogster1384** [comment]
It works!!! Thank you so much for the help!
