### ISSUE TITLE
Game crash while trying to load a custom layout

### ISSUE THREAD

**Issue by Jakob423** [Sewer56/Riders.Tweakbox#22]
[SonicRiders.exe.19916.zip](https://github.com/Sewer56/Riders.Tweakbox/files/7786392/SonicRiders.exe.19916.zip)
[2021-12-28 15.23.07 ~ SonicRiders.txt](https://github.com/Sewer56/Riders.Tweakbox/files/7786491/2021-12-28.15.23.07.SonicRiders.txt)

I was making a Layout with editor layout and after I was done, I try to load my custom Layout it will crash instead.  It is now impossible to access my custom layout.  The log might not help because it shows no error, but I will send it just in case.  

P.S. this is 7.0v of Tweakbox so the stable version should be fine.

**Comment by Sewer56** [comment]
Please update the layout.

Chances are that you either placed an object that is not available on the stage, or you put too many objects of the same type in proximity.

**Comment by Jakob423** [comment]
[Fly hopes buff.zip](https://github.com/Sewer56/Riders.Tweakbox/files/7787065/Fly.hopes.buff.zip)
I have right here, is in Digital Dimension.

**Comment by Jakob423** [comment]
**UPDATE**, It looks like it decides to fix itself.  Probably another windows 11 moment.  Sorry, everyone no issue here.
