### ISSUE TITLE
game does not launch from Reloaded, requiring the launcher instead

### ISSUE THREAD

**Issue by petran79** [Sewer56/Riders.Tweakbox#24]
I added the sonicriders no cd exe to the app and loaded the mod, however reloader refuses to load the game
It has to run from the launcher instead.

**Comment by Sewer56** [comment]
Tweakbox is supposed to patch this behaviour.

Can you provide a Reloaded log? 
Refer to: https://sewer56.dev/Riders.Tweakbox/reporting-issues/

**Comment by petran79** [comment]
It was an error of my part because I had created a separate reloaded directory for sonic riders to avoid confusion with mods. Reloaded was already installed on the folder of another game with mods and I had to use that  folder instead.
