### ISSUE TITLE
Game doesn't start with Tweakbox enabled

### ISSUE THREAD

**Issue by MilesFox92** [Sewer56/Riders.Tweakbox#28]
It doesnt crash or anything - it just doesnt start. RLD's console appears for around 3 seconds and then silently closes

**Comment by Sewer56** [comment]
Anyway, can you provide the crash info?

https://sewer56.dev/Riders.Tweakbox/reporting-issues/

Also try version 0.7.0 if you haven't already: https://cdn.discordapp.com/attachments/979471933382983780/979472056515166349/Riders.Tweakbox0.7.0-rc3.7z

=========
Note:

There will probably not be any fixes to Tweakbox for a long time. 

I have 1 year's worth of backlog stuff that are non-Riders related.

**Comment by MilesFox92** [comment]
0.7.0 works like a charm, huge thanks! And somehow 0.6.7 started working after I tried the 0.7.0 :/
But here's the log from when it was not working. No CrashDump generated though

[2023-09-16 08.55.53 ~ SonicRiders.txt](https://github.com/Sewer56/Riders.Tweakbox/files/12640302/2023-09-16.08.55.53.SonicRiders.txt)

**Comment by Sewer56** [comment]
If it works, it works :p
