### ISSUE TITLE
Game doesn't start with Tweakbox enabled

### ISSUE THREAD

**Issue by knuckleslee** [Sewer56/Riders.Tweakbox#30]
When I enable tweakbox, the command line window display an error message and then close, the game doesn't start.
This mod works on my other two computers, but not on my main one

.NET 8.0.6 x86/x64 installed
Reloaded-II 1.27.10
Tweakbox 0.7.1

Error message:
Fatal error. Invalid Program: attempted to call a UnmanagedCallersOnly method from managed code.
Fatal error while logging another fatal error.
Fatal error while logging another fatal error.

**Comment by Sewer56** [comment]
For Crash Dump info, see this https://sewer56.dev/Riders.Tweakbox/reporting-issues/

**Comment by Sewer56** [comment]
Can you boot the game unmodded? Am curious.

As for the crash dump, I was thinking of the `.dmp` file, it would contain more info about the issue.

**Comment by knuckleslee** [comment]
> Can you boot the game unmodded? Am curious.
> As for the crash dump, I was thinking of the `.dmp` file, it would contain more info about the issue.
The game works fine on my main pc, with or without mod.
just tweakbox not working

here's `.dmp` file
[SonicRiders.exe.22540.dmp](https://github.com/user-attachments/files/15791564/SonicRiders.exe.22540.dmp)

**Comment by Sewer56** [comment]
I'm not sure of the exact reason why it happens, but I think it's related to fraps.

**Comment by knuckleslee** [comment]
Oh my God, the problem was solved after I closed FRAPS.
I've been repeatedly installing/uninstalling various versions of the .NET runtime these past few days and couldn't solve it, so I came here for help. Your suggestion was very effective, thank you very much.
At the same time, thank you for making this convenient mod.

**Comment by Sewer56** [comment]
No worries, and of course, have fun and good luck :p

I did not think I'd see Fraps in 2024, but here we are 😆
